[disgo]
    listen                     = ":10000"
    broadcast                  = "127.0.0.1:10000"
    [disgo.etcd]
        servers                = "127.0.0.1:4001"
        ttl                    = 15

[logging]
    enabled                    = true
    [logging.trace]
        file                   = ""
        stdout                 = false
        stderr                 = false
        color                  = false
    [logging.debug]
        file                   = ""
        stdout                 = true
        stderr                 = false
        color                  = false
    [logging.info]
        file                   = ""
        stdout                 = true
        stderr                 = false
        color                  = false
    [logging.warn]
        file                   = ""
        stdout                 = true
        stderr                 = false
        color                  = false
    [logging.error]
        file                   = ""
        stdout                 = true
        stderr                 = false
        color                  = false

[Article]
    enabled                    = false

[Feed]
    enabled                    = false

[Manager]
    enabled                    = false
    startup                    = true
    [Manager.article]
        tick                   = "15s"
    [Manager.feed]
        tick                   = "30s"
        downloaddelay          = "-2h0m0s"

[Publication]
    enabled                    = false

[Search]
    enabled                    = false
    mongodb                    = "campbeltown.ocular8.net:27017,highland.ocular8.net:27017,island.ocular8.net:27017"

[Social]
    enabled                    = false

[Stats]
    enabled                    = false
    rate                       = 1
    reconnect                  = "10m"
    statsd                     = "stats.lowland.ocular8.net:8125"

[StorageReader]
    enabled                    = false
    mongodb                    = "campbeltown.ocular8.net:27017,highland.ocular8.net:27017,island.ocular8.net:27017"
    prefix                     = "300brand_"

[StorageWriter]
    enabled                    = false
    mongodb                    = "campbeltown.ocular8.net:27017,highland.ocular8.net:27017,island.ocular8.net:27017"
    prefix                     = "300brand_"

[WebAPI]
    enabled                    = false
    httplisten                 = ":8080"
